# Generated by Django 4.2 on 2023-12-11 06:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('experience_required', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('duration_type', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH')], max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='duration must be an integer', null=True)),
                ('currency', models.CharField(choices=[('RS', 'RUPPEES'), ('USD', 'DOLLAR')], max_length=3)),
                ('salary', models.PositiveIntegerField(help_text='job salary')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('skill_required', models.ManyToManyField(to='accounts.skill')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('star_rating', models.PositiveIntegerField(default=0)),
                ('review_message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to=settings.AUTH_USER_MODEL)),
                ('rating_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('INPROCESS', 'INPROCESS'), ('DENIED', 'DENIED')], default='INPROCESS', max_length=10)),
                ('resume', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc'], message='only pdf, txt, doc extensions allowed')])),
                ('bid', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('RS', 'RUPPEES'), ('USD', 'DOLLAR')], max_length=3)),
                ('message', models.TextField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=7)),
                ('remaining', models.PositiveIntegerField(null=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='job.jobproposal')),
            ],
        ),
    ]
