# Generated by Django 4.2 on 2023-12-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='job.jobproposal'),
        ),
        migrations.AlterField(
            model_name='jobproposal',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('INPROCESS', 'INPROCESS')], default='INPROCESS', max_length=10),
        ),
    ]
